# log config
logging:
  config: classpath:logback.xml
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://gateway.syswinsoft.com:45118
### xxl-job executor address
    executor:
      appname: xxl-job-executor
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
### xxl-job, access token
    accessToken: 